version: '3.4'

services:
  ideliverbotserver:
    image: ideliveybotserver
    build:
      context: src
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
