// Generated by gencpp from file delivery/Call.msg
// DO NOT EDIT!


#ifndef DELIVERY_MESSAGE_CALL_H
#define DELIVERY_MESSAGE_CALL_H

#include <ros/service_traits.h>


#include <delivery/CallRequest.h>
#include <delivery/CallResponse.h>


namespace delivery
{

struct Call
{

typedef CallRequest Request;
typedef CallResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Call
} // namespace delivery


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::delivery::Call > {
  static const char* value()
  {
    return "bd3e0142db41a8872e933337357dd05d";
  }

  static const char* value(const ::delivery::Call&) { return value(); }
};

template<>
struct DataType< ::delivery::Call > {
  static const char* value()
  {
    return "delivery/Call";
  }

  static const char* value(const ::delivery::Call&) { return value(); }
};


// service_traits::MD5Sum< ::delivery::CallRequest> should match
// service_traits::MD5Sum< ::delivery::Call >
template<>
struct MD5Sum< ::delivery::CallRequest>
{
  static const char* value()
  {
    return MD5Sum< ::delivery::Call >::value();
  }
  static const char* value(const ::delivery::CallRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::delivery::CallRequest> should match
// service_traits::DataType< ::delivery::Call >
template<>
struct DataType< ::delivery::CallRequest>
{
  static const char* value()
  {
    return DataType< ::delivery::Call >::value();
  }
  static const char* value(const ::delivery::CallRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::delivery::CallResponse> should match
// service_traits::MD5Sum< ::delivery::Call >
template<>
struct MD5Sum< ::delivery::CallResponse>
{
  static const char* value()
  {
    return MD5Sum< ::delivery::Call >::value();
  }
  static const char* value(const ::delivery::CallResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::delivery::CallResponse> should match
// service_traits::DataType< ::delivery::Call >
template<>
struct DataType< ::delivery::CallResponse>
{
  static const char* value()
  {
    return DataType< ::delivery::Call >::value();
  }
  static const char* value(const ::delivery::CallResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DELIVERY_MESSAGE_CALL_H
