// Generated by gencpp from file delivery/CallRequest.msg
// DO NOT EDIT!


#ifndef DELIVERY_MESSAGE_CALLREQUEST_H
#define DELIVERY_MESSAGE_CALLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delivery
{
template <class ContainerAllocator>
struct CallRequest_
{
  typedef CallRequest_<ContainerAllocator> Type;

  CallRequest_()
    {
    }
  CallRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::delivery::CallRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delivery::CallRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CallRequest_

typedef ::delivery::CallRequest_<std::allocator<void> > CallRequest;

typedef boost::shared_ptr< ::delivery::CallRequest > CallRequestPtr;
typedef boost::shared_ptr< ::delivery::CallRequest const> CallRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delivery::CallRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delivery::CallRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace delivery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delivery::CallRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery::CallRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery::CallRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery::CallRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery::CallRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery::CallRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delivery::CallRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::delivery::CallRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::delivery::CallRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delivery/CallRequest";
  }

  static const char* value(const ::delivery::CallRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delivery::CallRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::delivery::CallRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delivery::CallRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CallRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delivery::CallRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::delivery::CallRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DELIVERY_MESSAGE_CALLREQUEST_H
