// Generated by gencpp from file delivery/Cmd.msg
// DO NOT EDIT!


#ifndef DELIVERY_MESSAGE_CMD_H
#define DELIVERY_MESSAGE_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delivery
{
template <class ContainerAllocator>
struct Cmd_
{
  typedef Cmd_<ContainerAllocator> Type;

  Cmd_()
    : type()
    , num(0)
    , body()  {
    }
  Cmd_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , num(0)
    , body(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef int32_t _num_type;
  _num_type num;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _body_type;
  _body_type body;





  typedef boost::shared_ptr< ::delivery::Cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delivery::Cmd_<ContainerAllocator> const> ConstPtr;

}; // struct Cmd_

typedef ::delivery::Cmd_<std::allocator<void> > Cmd;

typedef boost::shared_ptr< ::delivery::Cmd > CmdPtr;
typedef boost::shared_ptr< ::delivery::Cmd const> CmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delivery::Cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delivery::Cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delivery::Cmd_<ContainerAllocator1> & lhs, const ::delivery::Cmd_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.num == rhs.num &&
    lhs.body == rhs.body;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delivery::Cmd_<ContainerAllocator1> & lhs, const ::delivery::Cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delivery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delivery::Cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery::Cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery::Cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery::Cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery::Cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery::Cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delivery::Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ce1e7c244927ca76a4c6cf091b0e309";
  }

  static const char* value(const ::delivery::Cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ce1e7c244927ca7ULL;
  static const uint64_t static_value2 = 0x6a4c6cf091b0e309ULL;
};

template<class ContainerAllocator>
struct DataType< ::delivery::Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delivery/Cmd";
  }

  static const char* value(const ::delivery::Cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delivery::Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string type\n"
"int32 num\n"
"string body\n"
;
  }

  static const char* value(const ::delivery::Cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delivery::Cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.num);
      stream.next(m.body);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delivery::Cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delivery::Cmd_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
    s << indent << "body: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.body);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELIVERY_MESSAGE_CMD_H
