// Generated by gencpp from file delivery/Map.msg
// DO NOT EDIT!


#ifndef DELIVERY_MESSAGE_MAP_H
#define DELIVERY_MESSAGE_MAP_H

#include <ros/service_traits.h>


#include <delivery/MapRequest.h>
#include <delivery/MapResponse.h>


namespace delivery
{

struct Map
{

typedef MapRequest Request;
typedef MapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Map
} // namespace delivery


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::delivery::Map > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::delivery::Map&) { return value(); }
};

template<>
struct DataType< ::delivery::Map > {
  static const char* value()
  {
    return "delivery/Map";
  }

  static const char* value(const ::delivery::Map&) { return value(); }
};


// service_traits::MD5Sum< ::delivery::MapRequest> should match
// service_traits::MD5Sum< ::delivery::Map >
template<>
struct MD5Sum< ::delivery::MapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::delivery::Map >::value();
  }
  static const char* value(const ::delivery::MapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::delivery::MapRequest> should match
// service_traits::DataType< ::delivery::Map >
template<>
struct DataType< ::delivery::MapRequest>
{
  static const char* value()
  {
    return DataType< ::delivery::Map >::value();
  }
  static const char* value(const ::delivery::MapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::delivery::MapResponse> should match
// service_traits::MD5Sum< ::delivery::Map >
template<>
struct MD5Sum< ::delivery::MapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::delivery::Map >::value();
  }
  static const char* value(const ::delivery::MapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::delivery::MapResponse> should match
// service_traits::DataType< ::delivery::Map >
template<>
struct DataType< ::delivery::MapResponse>
{
  static const char* value()
  {
    return DataType< ::delivery::Map >::value();
  }
  static const char* value(const ::delivery::MapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DELIVERY_MESSAGE_MAP_H
