// Generated by gencpp from file delivery/Status.msg
// DO NOT EDIT!


#ifndef DELIVERY_MESSAGE_STATUS_H
#define DELIVERY_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delivery
{
template <class ContainerAllocator>
struct Status_
{
  typedef Status_<ContainerAllocator> Type;

  Status_()
    : free(false)  {
    }
  Status_(const ContainerAllocator& _alloc)
    : free(false)  {
  (void)_alloc;
    }



   typedef uint8_t _free_type;
  _free_type free;





  typedef boost::shared_ptr< ::delivery::Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delivery::Status_<ContainerAllocator> const> ConstPtr;

}; // struct Status_

typedef ::delivery::Status_<std::allocator<void> > Status;

typedef boost::shared_ptr< ::delivery::Status > StatusPtr;
typedef boost::shared_ptr< ::delivery::Status const> StatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delivery::Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delivery::Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delivery::Status_<ContainerAllocator1> & lhs, const ::delivery::Status_<ContainerAllocator2> & rhs)
{
  return lhs.free == rhs.free;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delivery::Status_<ContainerAllocator1> & lhs, const ::delivery::Status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delivery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delivery::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery::Status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delivery::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "662d0577555df77dcaee5a646dd74f27";
  }

  static const char* value(const ::delivery::Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x662d0577555df77dULL;
  static const uint64_t static_value2 = 0xcaee5a646dd74f27ULL;
};

template<class ContainerAllocator>
struct DataType< ::delivery::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delivery/Status";
  }

  static const char* value(const ::delivery::Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delivery::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool free \n"
;
  }

  static const char* value(const ::delivery::Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delivery::Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.free);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delivery::Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delivery::Status_<ContainerAllocator>& v)
  {
    s << indent << "free: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.free);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELIVERY_MESSAGE_STATUS_H
